### ISSUE TITLE
use it with of 0.9

### ISSUE THREAD

**Issue by joaodafonseca** [naychrist/ofxRedparkSerial#1]
Any change to use this library with of 0.9? the example compiles but can't send or receive any serial, this is the console output:

2015-03-09 15:56:38.004 emptyExample[384:36509] ACC Connect
2015-03-09 15:56:38.005 emptyExample[384:36509] writeRscMessage - null session

thanks,
J

**Comment by naychrist** [comment]
Sorry but am no longer maintaining this lib.

**Comment by joaodafonseca** [comment]
ok, thanks for the response anyway
